// <auto-generated />
namespace MicWay.Driver.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class driver : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(driver));
        
        string IMigrationMetadata.Id
        {
            get { return "201901260023414_driver"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
